---
- name: generic
  hosts: all
  become: yes
  tasks:
    - name: install Intel microcode
      apt:
        name: intel-microcode
        state: present
      when: '"GenuineIntel" in ansible_processor'

    - name: install Broadcom BCM4321 firmware
      apt:
        name: firmware-b43-installer
        state: present
      when: ansible_product_name == "Macmini3,1"

    - name: enable PulseAudio mixer
      lineinfile:
        insertafter: '^;\s*flat-volumes\s*='
        regexp: '^\s*flat-volumes\s*='
        line: 'flat-volumes = no'
        path: /etc/pulse/daemon.conf
        owner: root
        group: root
        mode: 0644

    - name: install additional packages
      apt:
        name:
          - needrestart
          - thunderbird
          - transmission
          - weechat
        state: present

    - name: detect if Xfce is installed
      stat:
        path: /usr/bin/xfwm4
      register: xfwm4_st

    - name: allow automatic suspend for Xfce
      copy:
        src: files/{{ ansible_distribution_release }}/enable-suspend.pkla
        dest: /etc/polkit-1/localauthority/50-local.d/enable-suspend.pkla
        owner: root
        group: root
        mode: 0644
      when: xfwm4_st.stat.isreg is defined and xfwm4_st.stat.isreg == True

    - name: setup zram
      import_tasks: zram.yml
      when: zram_use_threshold_mb is defined and ansible_memory_mb.real.total < zram_use_threshold_mb
