---
- name: setup sound
  hosts: all
  become: yes
  tasks:
    - name: enable PulseAudio mixer
      lineinfile:
        insertafter: '^;\s*flat-volumes\s*='
        regexp: '^\s*flat-volumes\s*='
        line: 'flat-volumes = no'
        path: /etc/pulse/daemon.conf
        owner: root
        group: root
        mode: 0644

- name: configure zramswap
  hosts: low_memory
  become: yes
  tasks:
    - name: install zram-tools and earlyoom
      apt:
        name:
          - zram-tools
          - earlyoom
        state: present

    - name: write zram-tools defaults
      copy:
        src: files/{{ ansible_distribution_release }}/zramswap
        dest: /etc/default/zramswap
        owner: root
        group: root
        mode: 0644

    - name: write sysctl configuration
      copy:
        src: files/{{ ansible_distribution_release }}/sysctl.conf
        dest: /etc/sysctl.d/local.conf
        owner: root
        group: root
        mode: 0644

    - name: disable swap entries in /etc/fstab
      replace:
        path: /etc/fstab
        owner: root
        group: root
        mode: 0644
        regexp: '^([^#]\S+\s+\S+\s+swap\s+[^\n]*)$'
        replace: '#\1'

- name: setup Xfce
  hosts: xfce
  become: yes
  tasks:
  - name: enable automatic suspend
    copy:
      src: files/{{ ansible_distribution_release }}/enable-suspend.pkla
      dest: /etc/polkit-1/localauthority/50-local.d/enable-suspend.pkla
      owner: root
      group: root
      mode: 0644

  - name: install additional packages for Xfce
    apt:
      name: compton
      state: present
